# Generated by Django 4.2.6 on 2023-10-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to='images')),
                ('Designation', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=12)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
